export const objectMenuGlobal = {

    "AllMenu": [
        {
            "RowID": 1,
            "Title": "Công việc cá nhân",
            "nameEN": "Personal work",
            "goscreen": "ManHinh_CongViecCaNhan",
            "screen": "sc_CongViecCaNhan",
            "linkicon": require('../../../images/imgAppJee/icMNCV_1.png'),
            "isShow": true,
            "params": {},
            "LangueKey": "vieccanhan"
        },
        {
            "RowID": 2,
            "Title": "Giao Việc",
            "nameEN": "Assign",
            "goscreen": "sc_GiaoViec",
            "screen": "sc_GiaoViec",
            "linkicon": require('../../../images/imgAppJee/icMNCV_2.png'),
            "isShow": true,
            "params": {},
            "LangueKey": "vieccanhan"
        },
        {
            "RowID": 3,
            "Title": "Nhiệm vụ phụ trách",
            "nameEN": "Duty in charge",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNCV_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 4,
            "Title": "Việc của nhân viên cấp dưới",
            "nameEN": "Work of junior staff",
            "goscreen": "sc_ViecNhanVIenCapDuoi",
            "screen": "sc_ViecNhanVIenCapDuoi",
            "linkicon": require('../../../images/imgAppJee/icMNCV_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 5,
            "Title": "Dự án/công việc phòng ban phụ trách",
            "nameEN": "Project/work of department esponsible",
            "goscreen": "sc_QuanLyDuAn",
            "screen": "sc_QuanLyDuAn",
            "linkicon": require('../../../images/imgAppJee/icMNCV_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 6,
            "Title": "Công việc theo dõi",
            "nameEN": "Work monitor",
            "goscreen": "sc_CongViecTheoDoi",
            "screen": "sc_CongViecTheoDoi",
            "linkicon": require('../../../images/imgAppJee/icMNCV_6.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 7,
            "Title": "Nghỉ phép / công tác",
            "nameEN": "Day off / go on business",
            "goscreen": "sc_NghiPhep",
            "screen": "sc_NghiPhep",
            "linkicon": require('../../../images/imgAppJee/icMNNS_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 8,
            "Title": "Làm thêm giờ",
            "nameEN": "Overtime",
            "goscreen": "sc_TangCa",
            "screen": "sc_Tangca",
            "linkicon": require('../../../images/imgAppJee/icMNNS_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 9,
            "Title": "Đổi ca làm việc",
            "nameEN": "Make shift",
            "goscreen": "sc_DoiCaLamViec",
            "screen": "sc_DoiCaLamViec",
            "linkicon": require('../../../images/imgAppJee/icMNNS_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 10,
            "Title": "Giải trình chấm công",
            "nameEN": "Timekeeping explanation",
            "goscreen": "sc_GTChamCong",
            "screen": "sc_GTChamCong",
            "linkicon": require('../../../images/imgAppJee/icMNNS_6.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 11,
            "Title": "Bảng công",
            "nameEN": "Timesheet",
            "goscreen": "sc_BangChamCong",
            // "screen": "sc_BangCong",
            "linkicon": require('../../../images/imgAppJee/icMNNS_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 12,
            "Title": "Phiếu lương",
            "nameEN": "Paycheck",
            "goscreen": "sc_BangLuongChiTiet",
            // "screen": "sc_BangLuongChiTiet",
            "linkicon": require('../../../images/imgAppJee/icMNNS_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 13,
            "Title": "Duyệt đơn",
            "nameEN": "Approve application",
            "goscreen": "sc_QuanLyDuyet",
            "screen": "sc_homeduyet",
            "linkicon": require('../../../images/imgAppJee/icMNNS_7.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 14,
            "Title": "Phép nhân viên",
            "nameEN": "Day off of staff",
            "goscreen": "sc_PhepTonNhanVien",
            "screen": "sc_PhepTonNhanVien",
            "linkicon": require('../../../images/imgAppJee/icMNNS_8.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 15,
            "Title": "Quản lý nhân viên",
            "nameEN": "Staff manager",
            "goscreen": "sc_QuanLyNhanVien",
            // "screen": "sc_QuanLyNhanVien",
            "linkicon": require('../../../images/imgAppJee/icMNNS_10.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 16,
            "Title": "Quản lý chấm công",
            "nameEN": "Time attendance manager",
            "goscreen": "sc_QuanLyChamCong",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNNS_9.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 17,
            "Title": "Gửi yêu cầu",
            "nameEN": "Send request",
            "goscreen": "sc_GuiYeuCau",
            "screen": "sc_DSGuiYeuCau",
            "linkicon": require('../../../images/imgAppJee/icMNYC_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 18,
            "Title": "Duyệt yêu cầu",
            "nameEN": "Browse request",
            "goscreen": "sc_DuyetYeuCau",
            "screen": "sc_DSDuyetYeuCau",
            "linkicon": require('../../../images/imgAppJee/icMNYC_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 19,
            "Title": "Cài đặt yêu cầu",
            "nameEN": "Setting request",
            "goscreen": "sc_CaiDatYeuCau",
            "screen": "sc_LoaiYeuCau",
            "linkicon": require('../../../images/imgAppJee/icSettingRequest.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 20,
            "Title": "Đăng ký sử dụng tài sản",
            "nameEN": "Register to use asset",
            "goscreen": "sc_JeeHanhChanh",
            "screen": "sc_DangKyTaiSan",
            "linkicon": require('../../../images/imgAppJee/icMNHC_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 21,
            "Title": "Đăng ký sử dụng xe",
            "nameEN": "Register to use the car",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 22,
            "Title": "Yêu cầu cấp phát tài sản",
            "nameEN": "Request allocate asset",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 23,
            "Title": "Yêu cầu cấp phát văn phòng phẩm",
            "nameEN": "Request allocate stationery",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 24,
            "Title": "Duyệt yêu cầu văn phòng phẩm",
            "nameEN": "Browse Request allocate stationery",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 25,
            "Title": "Kiểm kê tài sản",
            "nameEN": "Asset inventory",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_6.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 26,
            "Title": "Quản lý cuộc họp",
            "nameEN": "Meeting manager",
            "goscreen": "sc_HomeCuocHop",
            "screen": "sc_QuanLyCuocHop",
            "linkicon": require('../../../images/imgAppJee/MenuCuocHop.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 27,
            "Title": "Công việc hết hạn trong ngày",
            "nameEN": "Job expires within day",
            "goscreen": "sc_CVHetHanTrongNgay",
            "screen": "sc_CVHetHanTrongNgay",
            "linkicon": require('../../../images/imgAppJee/icMNCV_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 28,
            "Title": "Đăng ký khuôn mặt",
            "nameEN": "Register face",
            "goscreen": "sc_DKFaceNV",
            "screen": "sc_DangkyFace",
            "linkicon": require('../../../images/imgAppJee/icDangKyKhuonMat.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 29,
            "Title": "Máy chấm công",
            "nameEN": "Timekeeper",
            "goscreen": "sc_MayChamCong",
            "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMayChamCong.png'),
            "isShow": true,
            "params": { isMode: 3 },
        },
        {
            "RowID": 30,
            "Title": "Chấm công nhân viên",
            "nameEN": "Staff timekeeping",
            "goscreen": "sc_ChamCongNhanVien",
            "screen": "",
            "linkicon": require('../../../images/imgAppJee/icChamCongNV.png'),
            "isShow": true,
            "params": { isMode: 2 },
        },
        {
            "RowID": 31,
            "Title": "Công việc lặp lại",
            "nameEN": "Repetitive work",
            "goscreen": "ManHinh_CongViecLapLai",
            "screen": "sc_CongViecLapLai",
            "linkicon": require('../../../images/imgAppJee/jwCongViecLapLai.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 32,
            "Title": "Quản lý tài sản dùng chung",
            "nameEN": "Shared asset management",
            "goscreen": "sc_JeeHanhChanhAdmin",
            "screen": "sc_QuanLiTaiSan",
            "linkicon": require('../../../images/imgAppJee/DuyetTaiSan.png'),
            "isShow": true,
            "params": {},
        },
    ],
    "MenuCongViec": [
        {
            "RowID": 1,
            "Title": "Công việc cá nhân",
            "nameEN": "Personal work",
            "goscreen": "ManHinh_CongViecCaNhan",
            "screen": "sc_CongViecCaNhan",
            "linkicon": require('../../../images/imgAppJee/icMNCV_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 2,
            "Title": "Giao Việc",
            "nameEN": "Assign",
            "goscreen": "sc_GiaoViec",
            "screen": "sc_GiaoViec",
            "linkicon": require('../../../images/imgAppJee/icMNCV_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 3,
            "Title": "Nhiệm vụ phụ trách",
            "nameEN": "Duty in charge",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNCV_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 4,
            "Title": "Việc của nhân viên cấp dưới",
            "nameEN": "Work of junior staff",
            "goscreen": "sc_ViecNhanVIenCapDuoi",
            "screen": "sc_ViecNhanVIenCapDuoi",
            "linkicon": require('../../../images/imgAppJee/icMNCV_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 5,
            "Title": "Dự án/công việc phòng ban phụ trách",
            "nameEN": "Project/work of department esponsible",
            "goscreen": "sc_QuanLyDuAn",
            "screen": "sc_QuanLyDuAn",
            "linkicon": require('../../../images/imgAppJee/icMNCV_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 6,
            "Title": "Công việc theo dõi",
            "nameEN": "Work monitor",
            "goscreen": "sc_CongViecTheoDoi",
            "screen": "sc_CongViecTheoDoi",
            "linkicon": require('../../../images/imgAppJee/icMNCV_6.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 27,
            "Title": "Công việc hết hạn trong ngày",
            "nameEN": "Job expires within day",
            "goscreen": "sc_CVHetHanTrongNgay",
            "screen": "sc_CVHetHanTrongNgay",
            "linkicon": require('../../../images/imgAppJee/icMNCV_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 31,
            "Title": "Công việc lặp lại",
            "nameEN": "Repetitive work",
            "goscreen": "ManHinh_CongViecLapLai",
            "screen": "sc_CongViecLapLai",
            "linkicon": require('../../../images/imgAppJee/jwCongViecLapLai.png'),
            "isShow": true,
            "params": {},
        },
    ],
    "MenuNhanSu": [
        {
            "RowID": 7,
            "Title": "Nghỉ phép/công tác",
            "nameEN": "Day off / go on business",
            "goscreen": "sc_NghiPhep",
            "screen": "sc_NghiPhep",
            "linkicon": require('../../../images/imgAppJee/icMNNS_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 8,
            "Title": "Làm thêm giờ",
            "nameEN": "Overtime",
            "goscreen": "sc_TangCa",
            "screen": "sc_Tangca",
            "linkicon": require('../../../images/imgAppJee/icMNNS_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 9,
            "Title": "Đổi ca làm việc",
            "nameEN": "Make shift",
            "goscreen": "sc_DoiCaLamViec",
            "screen": "sc_DoiCaLamViec",
            "linkicon": require('../../../images/imgAppJee/icMNNS_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 10,
            "Title": "Giải trình chấm công",
            "nameEN": "Timekeeping explanation",
            "goscreen": "sc_GTChamCong",
            "screen": "sc_GTChamCong",
            "linkicon": require('../../../images/imgAppJee/icMNNS_6.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 11,
            "Title": "Bảng công",
            "nameEN": "Timesheet",
            "goscreen": "sc_BangChamCong",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNNS_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 12,
            "Title": "Phiếu lương",
            "nameEN": "Paycheck",
            "goscreen": "sc_BangLuongChiTiet",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNNS_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 13,
            "Title": "Duyệt đơn",
            "nameEN": "Approve application",
            "goscreen": "sc_QuanLyDuyet",
            "screen": "sc_homeduyet",
            "linkicon": require('../../../images/imgAppJee/icMNNS_7.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 14,
            "Title": "Phép nhân viên",
            "nameEN": "Day off of staff",
            "goscreen": "sc_PhepTonNhanVien",
            "screen": "sc_PhepTonNhanVien",
            "linkicon": require('../../../images/imgAppJee/icMNNS_8.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 15,
            "Title": "Quản lý nhân viên",
            "nameEN": "Staff manager",
            "goscreen": "sc_QuanLyNhanVien",
            // "screen": "sc_QuanLyNhanVien",
            "linkicon": require('../../../images/imgAppJee/icMNNS_10.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 16,
            "Title": "Quản lý chấm công",
            "nameEN": "Time attendance manager",
            "goscreen": "sc_QuanLyChamCong",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNNS_9.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 28,
            "Title": "Đăng ký khuôn mặt",
            "nameEN": "Register face",
            "goscreen": "sc_DKFaceNV",
            "screen": "sc_DangkyFace",
            "linkicon": require('../../../images/imgAppJee/icDangKyKhuonMat.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 29,
            "Title": "Máy chấm công",
            "nameEN": "Timekeeper",
            "goscreen": "sc_MayChamCong",
            "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMayChamCong.png'),
            "isShow": true,
            "params": { isMode: 3 },
        },
        {
            "RowID": 30,
            "Title": "Chấm công nhân viên",
            "nameEN": "Staff timekeeping",
            "goscreen": "sc_ChamCongNhanVien",
            "screen": "",
            "linkicon": require('../../../images/imgAppJee/icChamCongNV.png'),
            "isShow": true,
            "params": { isMode: 2 },
        },
    ],
    "MenuYeuCau": [
        {
            "RowID": 17,
            "Title": "Gửi yêu cầu",
            "nameEN": "Send request",
            "goscreen": "sc_GuiYeuCau",
            "screen": "sc_DSGuiYeuCau",
            "linkicon": require('../../../images/imgAppJee/icMNYC_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 18,
            "Title": "Duyệt yêu cầu",
            "nameEN": "Browse request",
            "goscreen": "sc_DuyetYeuCau",
            "screen": "sc_DSDuyetYeuCau",
            "linkicon": require('../../../images/imgAppJee/icMNYC_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 19,
            "Title": "Cài đặt yêu cầu",
            "nameEN": "Setting request",
            "goscreen": "sc_CaiDatYeuCau",
            "screen": "sc_LoaiYeuCau",
            "linkicon": require('../../../images/imgAppJee/icSettingRequest.png'),
            "isShow": true,
            "params": {},
        },
    ],
    "MenuHanhChinh": [
        {
            "RowID": 32,
            "Title": "Quản lý tài sản dùng chung",
            "nameEN": "Shared asset management",
            "goscreen": "sc_JeeHanhChanhAdmin",
            "screen": "sc_QuanLiTaiSan",
            "linkicon": require('../../../images/imgAppJee/DuyetTaiSan.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 20,
            "Title": "Đăng ký sử dụng tài sản",
            "nameEN": "Register to use asset",
            "goscreen": "sc_JeeHanhChanh",
            "screen": "sc_DangKyTaiSan",
            "linkicon": require('../../../images/imgAppJee/icMNHC_1.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 21,
            "Title": "Đăng ký sử dụng xe",
            "nameEN": "Register to use the car",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_2.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 22,
            "Title": "Yêu cầu cấp phát tài sản",
            "nameEN": "Request allocate asset",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_3.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 23,
            "Title": "Yêu cầu cấp phát văn phòng phẩm",
            "nameEN": "Request allocate stationery",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_5.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 24,
            "Title": "Duyệt yêu cầu văn phòng phẩm",
            "nameEN": "Browse Request allocate stationery",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_4.png'),
            "isShow": true,
            "params": {},
        },
        {
            "RowID": 25,
            "Title": "Kiểm kê tài sản ",
            "nameEN": "Asset inventory",
            "goscreen": "Modal_devoloping",
            // "screen": "",
            "linkicon": require('../../../images/imgAppJee/icMNHC_6.png'),
            "isShow": true,
            "params": {},
        },
    ],
    "MenuCuocHop": [
        {
            "RowID": 26,
            "Title": "Quản lý cuộc họp",
            "nameEN": "Meeting manager",
            "goscreen": "sc_HomeCuocHop",
            "screen": "sc_QuanLyCuocHop",
            "linkicon": require('../../../images/imgAppJee/MenuCuocHop.png'),
            "isShow": true,
            "params": {},
        },
    ],
}