
const IConMenuHome = {
    icTime: require('./imgAppJeeHR/ictime.png'),
    icGoScreen: require('./imgAppJeeHR/icGoScreen.png'),
    icPhienban: require('./imgAppJeeHR/icPhienban.png'),
    icGoBackWhite: require('./imgAppJeeHR/icGoBackWhite.png'),
    icThongTinCaNhan: require('./imgAppJeeHR/icThongTinCaNhan.png'),
    icGuiDonXinPhep: require('./imgAppJeeHR/icGuiDonXinPhep.png'),
    icDangKyTangCa: require('./imgAppJeeHR/icDangKyTangCa.png'),
    icXemBangChamCong: require('./imgAppJeeHR/icXemBangChamCong.png'),
    icXemBangLuong: require('./imgAppJeeHR/icXemBangLuong.png'),
    icPhepTonNhanVien: require('./imgAppJeeHR/icPhepTonNhanVien.png'),
    icDuLieuChamCong: require('./imgAppJeeHR/icDuLieuChamCong.png'),
    icBTNghiPhep: require('./imgAppJeeHR/icBTNghiPhep.png'),
    icBTBangcong: require('./imgAppJeeHR/icBTBangcong.png'),
    icBTTangca: require('./imgAppJeeHR/icBTTangca.png'),
    icBTTatca: require('./imgAppJeeHR/icBTTatca.png'),
    icBTNghiPhepA: require('./imgAppJeeHR/icBTNghiPhepA.png'),
    icBTBangcongA: require('./imgAppJeeHR/icBTBangcongA.png'),
    icBTBangluongA: require('./imgAppJeeHR/icBTBangluongA.png'),
    icBTTangcaA: require('./imgAppJeeHR/icBTTangcaA.png'),
    icBTTatcaA: require('./imgAppJeeHR/icBTTatCaA.png'),
    icNotificationBellA: require('./imgAppJeeHR/icNotificationBellA.png'),
    icNotificationBell: require('./imgAppJeeHR/icNotificationBell.png'),
    icDropPopUp: require('./imgAppJeeHR/icDropPopUp.png'),
    icBTThongTinCaNhan: require('./imgAppJeeHR/icBTThongTinCaNhan.png'),
    icBTThongTinCaNhanA: require('./imgAppJeeHR/icBTThongTinCaNhanA.png'),
    icBTCaiDat: require('./imgAppJeeHR/icBTCaiDat.png'),
    icBTCaiDatA: require('./imgAppJeeHR/icBTCaiDatA.png'),
    icChamCong: require('./imgAppJeeHR/icChamCong.png'),
    icThongBaoNhanSu: require('./imgAppJeeHR/icThongBaoNhanSu.png'),
    icDoiCaLamViec: require('./imgAppJeeHR/icDoiCaLamViec.png'),
    icCaiDatCN: require('./imgAppJeeHR/icCaiDatCN.png'),
    icMenuCCNV: require('./imgAppJeeHR/icMenuCCNV.png'),
    icMenuCCCam: require('./imgAppJeeHR/icMenuCCCam.png'),
    icDKFaceNV: require('./imgAppJeeHR/icDKFaceNV.png'),
    icDelFace: require('./imgAppJeeHR/icDelFace.png'),
}

const ImagesJeeHR = {
    icMenuCCWF: require('./imgAppJeeHR/icMenuCCWF.png'),
    icCheckedWifi: require('./imgAppJeeHR/icCheckedWifi.png'),
    icUnCheckedWifi: require('./imgAppJeeHR/icUnCheckedWifi.png'),
    icCamera: require('./imgAppJeeHR/icCamera.png'),
    icDoiMatKhau: require('./imgAppJeeHR/icdoimatkhau.png'),
    icNgonNgu: require('./imgAppJeeHR/icngonngu.png'),
    icThongTin: require('./imgAppJeeHR/icthongtin.png'),
    icDangXuat: require('./imgAppJeeHR/icdangxuat.png'),
    JeehrUsername: require('./imgAppJeeHR/icUsername.png'),
    JeehrPassword: require('./imgAppJeeHR/icPassword.png'),
    JeehrShowpass: require('./imgAppJeeHR/icShowpass.png'),
    JeehrHidepass: require('./imgAppJeeHR/icHidepass.png'),
    JeeHrbackgroundld: require('./imgAppJeeHR/imgbackgroundld.png'),
    JeeHrbackgroundldX: require('./imgAppJeeHR/imgbackgroundldX.png'),
    JeeHrbackground: require('./imgAppJeeHR/imgbackground.png'),//backgroundtopX
    JeeHrbackgroundtopX: require('./imgAppJeeHR/backgroundtopX.png'),
    JeeHrbackgroundtop: require('./imgAppJeeHR/backgroundtop.png'),
    JeeHrbackgroundX: require('./imgAppJeeHR/imgbackgroundX.png'),
    JeeHrBig: require('./imgAppJeeHR/icjeehrbig.png'),
    JeeGreen: require('./imgAppJeeHR/logoText.png'),
    JeeHricTop: require('./imgAppJeeHR/icjeehrtop.png'),
    JeeAvatar: require('./imgAppJeeHR/avatar.png'),
    JeeAvatarBig: require('./imgAppJeeHR/JeeAvatarBig.png'),
    JeeCheck: require('./imgAppJeeHR/Check.png'),
    JeeUnCheck: require('./imgAppJeeHR/UnCheck.png'),
    JeeCloseModal: require('./imgAppJeeHR/close-modal.png'),
    icLocationRefresh: require('./imgAppJeeHR/icLocationRefresh.png'),
    icShowLocation: require('./imgAppJeeHR/icShowLocation.png'),
    icReviewFace: require('./imgAppJeeHR/icReviewFace.png'),
    icFinger: require('./imgAppJeeHR/finger.png'),
    icDropdownNew: require('./imgAppJeeHR/icDropdownNew.png'),
    //
    icDuyetPhep: require('./imgAppJeeHR/icDuyetPhep.png'),
    icLichSu: require('./imgAppJeeHR/icLichSu.png'),
    icDropGreen: require('./imgAppJeeHR/icDropGreen.png'),
    icAva: require('./imgAppJeeHR/icAva.png'),
    icTimKiem: require('./imgAppJeeHR/icTimKiem.png'),
    icCalanderTimKiem: require('./imgAppJeeHR/icCalanderTimKiem.png'),
    icSearch: require('./imgAppJeeHR/icSearch.png'),
    icDeleteItem: require('./imgAppJeeHR/deleteItem.png'),
    icFilterNew: require('./imgAppJeeHR/FilterNew.png'),
    icAddress: require('./imgAppJeeHR/Address.png'),

    //Bổ sung icDonThoiViec, icDuyetPhep
    icDonThoiViec: require('./imgAppJeeHR/icDonThoiViec.png'),
    icQLDuyetPhep: require('./imgAppJeeHR/icQLDuyetPhep.png'),
    icDisconnect: require('./imgAppJeeHR/icDisconnect.png'),

    icDaNop: require('./imgAppJeeHR/checked.png'),
    icChuaNop: require('./imgAppJeeHR/cancel.png'),
    icDropDownD: require('./imgAppJeeHR/icDropDownUpD.png'),
    icDropDownU: require('./imgAppJeeHR/icDropDownUp.png'),

    icCalandaS: require('./imgAppJeeHR/icCalandaS.png'),



    //Bổ sung GiaoDienMoi
    icCameraMenu: require('./imgAppJeeHR/CameraMenu.png'),
    icClockMenu: require('./imgAppJeeHR/icClockMenu.png'),
    icBTGiaiTrinh: require('./imgAppJeeHR/icBTGiaiTrinh.png'),
    icBTGiaiTrinhA: require('./imgAppJeeHR/icBTGiaiTrinhA.png'),
    icBTThongBao: require('./imgAppJeeHR/icBTThongBao.png'),
    icBTThongBaoA: require('./imgAppJeeHR/icBTThongBaoA.png'),
    icWifiMenu: require('./imgAppJeeHR/icWifiMN.png'),
    icViTriMenu: require('./imgAppJeeHR/icViTriMN.png'),
    checkNew: require('./imgAppJeeHR/checkNew.png'),
    UncheckNew: require('./imgAppJeeHR/UncheckNew.png'),
    checkIn: require('./imgAppJeeHR/CheckIn.png'),
    checkOut: require('./imgAppJeeHR/CheckOut.png'),

    icAdd: require('./imgAppJeeHR/add.png'),
    icMinus: require('./imgAppJeeHR/minus.png'),
    man: require('./imgAppJeeHR/man.png'),

    expanded: require('./imgAppJeeHR/expand.png'),
    collapse: require('./imgAppJeeHR/collapse.png'),

    searchGreen: require('./imgAppJeeHR/search.png'),
    managerTime: require('./imgAppJeeHR/managerTime.png'),

    icThietBiViTri: require('./imgAppJeeHR/iconLocation.png'),
    icThietBiWifi: require('./imgAppJeeHR/iconWifi.png'),

    icSettingH: require('./imgAppJeeHR/settingHeader.png'),
    icAddH: require('./imgAppJeeHR/addHeader.png'),

    icPin: require('./imgAppJeeHR/pin.png'),
    icSort: require('./imgAppJeeHR/paper.png'),
    icChangeCam: require('./imgAppJeeHR/icChangeCam.png'),
    icSnapCam: require('./imgAppJeeHR/icSnap.png'),
    icBackCam: require('./imgAppJeeHR/icBackCamera.png'),
    icUploadPic: require('./imgAppJeeHR/photo.png'),
    icTakeCamera: require('./imgAppJeeHR/camera.png'),
    icWebcam: require('./imgAppJeeHR/webcam.png'),
    icClockHome: require('./imgAppJeeHR/icClockHome.png'),
    icReload: require('./imgAppJeeHR/refresh.png'),
    icQR: require('./imgAppJeeHR/qr.png'),
    icCloseWhite: require('./imgAppJeeHR/icCloseWhite.png'),
    icQRBG: require('./imgAppJeeHR/icQRBG.png'),


    /// Đăng ký 
    icCompany: require('./imgAppJeeHR/company.png'),
    icPhone: require('./imgAppJeeHR/phone.png'),
    icMail: require('./imgAppJeeHR/email.png'),
    icPerson: require('./imgAppJeeHR/user.png'),
    icName: require('./imgAppJeeHR/icname.png'),
    icGmail: require('./imgAppJeeHR/icgmail.png'),
    icUser: require('./imgAppJeeHR/icuser.png'),
    icPasswords: require('./imgAppJeeHR/icpasswords.png'),
    icCameras: require('./imgAppJeeHR/iccameras2.png'),
    icPhone: require('./imgAppJeeHR/icphone.png'),
    feedback: require('./imgAppJeeHR/feedback.png'),

    clock: require('./imgAppJeeHR/clock.png'),    //ic home
    icBGTopHome: require('./imgAppJeeHR/icBGTopHome.png'),
    icCalandarLeft: require('./imgAppJeeHR/icCalandarLeft.png'),
    icCalandarRight: require('./imgAppJeeHR/icCalandarRight.png'),
    //imagecomponent
    icTopModal: require('./imgAppJeeHR/icTopModal.png'),
    //end

    icKhongDuyet: require('./imgAppJeeHR/icKhongDuyet.png'),
    icDuyet: require('./imgAppJeeHR/icDuyet.png'),

    icDownBlue: require('./imgAppJeeHR/icDownBlue.png'),
    icDeleteCart: require('./imgAppJeeHR/icDeleteCart.png'),
    icGoBackGreen: require('./imgAppJeeHR/icGoBackGreen.png'),
    icGoBackback: require('./imgAppJeeHR/icGoBackback.png'),
    icChonNgay: require('./imgAppJeeHR/icChonNgay.png'),
    icTiengViet: require('./imgAppJeeHR/icTiengViet.png'),
    icTiengAnh: require('./imgAppJeeHR/icTiengAnh.png'),
    btnNext: require('./imgAppJeeHR/btnNext.png'),
    btnPre: require('./imgAppJeeHR/btnPre.png'),
    icCalendar: require('./imgAppJeeHR/icCalendar.png'),
    icRecycle: require('./imgAppJeeHR/icRecycle.png'),
    icListEmpty: require('./imgAppJeeHR/icListEmpty.png'),
    icDropdown: require('./imgAppJeeHR/icDropdown.png'),
    icIconDropDownNamNgangS: require('./imgAppJee/icIconDropDownNamNgang.png'),
    icClose: require('./imgAppJeeHR/icClose.png'),
    icAgree: require('./imgAppJeeHR/icAgree.png'),
    icCheck: require('./imgAppJeeHR/icCheck.png'),
    icUnCheck: require('./imgAppJeeHR/icUnCheck.png'),
    tabBottom: require('./imgAppJeeHR/tabBottom.png'),

    icThongBaoDaXem: require('./imgAppJeeHR/ThongBaoDaXem.png'),
    icThongBaoChuaXem: require('./imgAppJeeHR/ThongBaoChuaXem.png'),
}

const ImageTimekeeping = {
    icChangeCamera: require('./imgAppJeeHR/icChangeCam.png'),
    icSnapCamera: require('./imgAppJeeHR/icSnap.png'),
    icBackCamera: require('./imgAppJeeHR/icBackCamera.png'),
    iconEdit: require('./imgAppJeeHR/iconEdit.png'),
}

const ImageJee = {


    //IcMenu Tab 
    icMNTab_1: require('./imgAppJee/icMNTab_1.png'),
    icMNTab_2: require('./imgAppJee/icMNTab_2.png'),
    icMNTab_3: require('./imgAppJee/icMNTab_3.png'),
    icMNTab_4: require('./imgAppJee/icMNTab_4.png'),
    icMNTab_5: require('./imgAppJee/icMNTab_5.png'),


    //IcMenu Tab A 
    icMNTabA_1: require('./imgAppJee/icMNTabA_1.png'),
    icMNTabA_2: require('./imgAppJee/icMNTabA_2.png'),
    icMNTabA_3: require('./imgAppJee/icMNTabA_3.png'),
    icMNTabA_4: require('./imgAppJee/icMNTabA_4.png'),
    icMNTabA_5: require('./imgAppJee/icMNTabA_5.png'),



    //IcMenu Công Việc 
    icMNCV_1: require('./imgAppJee/icMNCV_1.png'),
    icMNCV_2: require('./imgAppJee/icMNCV_2.png'),
    icMNCV_3: require('./imgAppJee/icMNCV_3.png'),
    icMNCV_4: require('./imgAppJee/icMNCV_4.png'),
    icMNCV_5: require('./imgAppJee/icMNCV_5.png'),
    icMNCV_6: require('./imgAppJee/icMNCV_6.png'),


    //IcMenu Hành Chính 
    icMNHC_1: require('./imgAppJee/icMNHC_1.png'),
    icMNHC_2: require('./imgAppJee/icMNHC_2.png'),
    icMNHC_3: require('./imgAppJee/icMNHC_3.png'),
    icMNHC_4: require('./imgAppJee/icMNHC_4.png'),
    icMNHC_5: require('./imgAppJee/icMNHC_5.png'),
    icMNHC_6: require('./imgAppJee/icMNHC_6.png'),
    icDuyetTaiSan: require('./imgAppJee/DuyetTaiSan.png'),

    //IcMenu Yêu cầu 

    icMNYC_1: require('./imgAppJee/icMNYC_1.png'),
    icMNYC_2: require('./imgAppJee/icMNYC_2.png'),
    icMNYC_3: require('./imgAppJee/icMNYC_3.png'),


    //IcMenu Nhân sự
    icMNNS_1: require('./imgAppJee/icMNNS_1.png'),
    icMNNS_2: require('./imgAppJee/icMNNS_2.png'),
    icMNNS_3: require('./imgAppJee/icMNNS_3.png'),
    icMNNS_4: require('./imgAppJee/icMNNS_4.png'),
    icMNNS_5: require('./imgAppJee/icMNNS_5.png'),
    icMNNS_6: require('./imgAppJee/icMNNS_6.png'),
    icMNNS_7: require('./imgAppJee/icMNNS_7.png'),
    icMNNS_8: require('./imgAppJee/icMNNS_8.png'),
    icMNNS_9: require('./imgAppJee/icMNNS_9.png'),
    icMNNS_10: require('./imgAppJee/icMNNS_10.png'),


    //Ic Xài Chung Sử Dụng Nhiều 
    icSave: require('./imgAppJee/icSave.png'),
    icDelete: require('./imgAppJee/icDelete.png'),
    icArrowBack: require('./imgAppJee/icArrowBack.png'),
    icMenuEmpty: require('./imgAppJee/icMenuEmpty.png'),
    icArrowNext: require('./imgAppJee/icArrowNext.png'),
    icHistoryJW: require('./imgAppJee/icHictoryJW.png'),
    //Ic Công việc cá nhân
    //Đến hạn
    icChat: require('./imgAppJee/Iconawesome_comment_alt.png'),
    icCalenda: require('./imgAppJee/icCalenda.png'),
    // icLich_ChiTietTQ
    icStar: require('./imgAppJee/icStar.png'),
    icNoStar: require('./imgAppJee/icNoStar.png'),
    icGoBack: require('./imgAppJee/icGoBack.png'),

    //Chitiet_tongquan 
    icLichChiTietTQ: require('./imgAppJee/icLich_ChiTietTQ.png'),
    icCoUuTienCao: require('./imgAppJee/icCoUuTienCao.png'),
    icCoUuTienThap: require('./imgAppJee/icCoUuTienThap.png'),
    icCoKhongUuTien: require('./imgAppJee/icCoKhongUuTien.png'),
    icThemVaoDuAn: require('./imgAppJee/icThemVaoDuAn.png'),
    icChonNguoiThamGia: require('./imgAppJee/icChonNguoiThamGia.png'),
    icLoc: require('./imgAppJee/icLoc.png'),

    //ChiTietDuAn
    icThemMoi: require('./imgAppJee/icCongThemMoi.png'),
    icTimKiemTheMoi: require('./imgAppJee/icTimKiemThemMoi.png'),
    icIconDropDown: require('./imgAppJee/icIconDropDown.png'),
    icIconDropDownNamNgang: require('./imgAppJee/icIconDropDownNamNgang.png'),

    //Chat
    icMessage: require('./imgAppJee/icMessage.png'),
    icDanhBa: require('./imgAppJee/icDanhBa.png'),
    icEditMessage: require('./imgAppJee/icEditMessage.png'),
    icGroup: require('./imgAppJee/icGroup.png'),
    icCheckChat: require('./imgAppJee/icCheckChat.png'),
    icUnCheckChat: require('./imgAppJee/icUnCheckChat.png'),
    icNextChat: require('./imgAppJee/icNextChat.png'),
    icWord: require('./imgAppJee/icWord.png'),
    icExcel: require('./imgAppJee/icExcel.png'),
    icPDF: require('./imgAppJee/icPDF.png'),
    icOptionChat: require('./imgAppJee/icOptionChat.png'),
    icSmileChat: require('./imgAppJee/icSmileChat.png'),
    icPictureChat: require('./imgAppJee/icPictureChat.png'),
    icLikeChat: require('./imgAppJee/icLikeChat.png'),
    icSendChat: require('./imgAppJee/icSendChat.png'),
    icKey: require('./imgAppJee/icKey.png'),
    icLeave: require('./imgAppJee/icLeave.png'),
    icInDam: require('./imgAppJee/icInDam.png'),
    icInNghien: require('./imgAppJee/icInNghien.png'),
    icGachChan: require('./imgAppJee/icGachChan.png'),
    icGachNgang: require('./imgAppJee/icGachNgang.png'),
    //homeScreen
    MenuCuocHop: require('./imgAppJee/MenuCuocHop.png'),
    icCVPT: require('./imgAppJee/icCVPT.png'),//công việc phụ trách
    icCVQH: require('./imgAppJee/icCVQH.png'), // công việc quá hạn
    icDAQH: require('./imgAppJee/icDAQH.png'),//dự án quá hạn
    icDKTC: require('./imgAppJee/icDKTC.png'),// đăng ký tăng ca
    icDNPCT: require('./imgAppJee/icDNPCT.png'), // đon nghỉ phép công tác
    icNVPT: require('./imgAppJee/icNVPT.png'), // nhiệm vụ phụ trách
    icNVTD: require('./imgAppJee/icNVTD.png'),// nhiệm vụ theo dõi
    icVHHTN: require('./imgAppJee/icVHHTN.png'), // việc hết hạn trong ngày
    icYCCD: require('./imgAppJee/icYCCD.png'), // yêu cầu chờ duyệt
    icYCJRCD: require('./imgAppJee/icYCJRCD.png'),// yêu cầu jee rej chờ duyệt
    icPlus: require('./imgAppJee/plus.png'),
    icPlusCheck: require('./imgAppJee/icPlusCheck.png'),
    icCheckSuccess: require('./imgAppJee/icCheckSuccess.png'),
    icCheckPlusTwo: require('./imgAppJee/icPlusCheckTwo.png'),
    icCheckSuccessTwo: require('./imgAppJee/icCheckSuccessTwo.png'),
    //Socail
    icBack: require('./imgAppJee/icioniciosarrowbackSocial.png'),
    icHomeSocial: require('./imgAppJee/icionicioshome.png'),
    icCongTySocial: require('./imgAppJee/iciconCongTy.png'),
    icNhomSocial: require('./imgAppJee/icIconNhom.png'),
    icTimKiemSocial: require('./imgAppJee/icIconTimKiem.png'),
    icBoLocSocial: require('./imgAppJee/icIconBoLoc.png'),
    icTinTucSocial: require('./imgAppJee/icIconTinTuc.png'),
    icMetroplay: require('./imgAppJee/icIconmetroplay.png'),
    icBaCham: require('./imgAppJee/icIconBaCham.png'),
    icBaChamdoc: require('./imgAppJee/icBaChamdoc.png'),
    icSoLike: require('./imgAppJee/icIconSoLike.png'),
    icLike: require('./imgAppJee/icIconLike.png'),
    icBinhLuan: require('./imgAppJee/icIconBinhLuan.png'),
    icLuuTru: require('./imgAppJee/icIconLuuTru.png'),
    icCamera: require('./imgAppJee/icIconCamera.png'),
    icMatcuoi: require('./imgAppJee/icIconmaterialinsertemoticon.png'),
    icLink: require('./imgAppJee/icIconmetroattachment.png'),
    icTimKiemSocial: require('./imgAppJee/icIconTimKiem.png'),
    icDelete_TimKiem: require('./imgAppJee/icIconDelete_TimKiem.png'),
    icBinhChon: require('./imgAppJee/Iconionic_md_checkmark_circle.png'),
    icSukien: require('./imgAppJee/Iconawesome_calendar_minus.png'),
    icThongbao: require('./imgAppJee/icIconmaterial_announcement.png'),
    icThaoluan: require('./imgAppJee/icIconionic_ios_chatbubbles.png'),
    icKhenthuong: require('./imgAppJee/icIcon_material_local_florist.png'),
    icBaivietdaluu: require('./imgAppJee/icIconionic_ios_bookmark.png'),
    icTatcabaidang: require('./imgAppJee/icIconmaterial_all_out.png'),
    icTaoBaiDang: require('./imgAppJee/icIconawesome_plus_circle.png'),
    icChonAnh: require('./imgAppJee/ic_Iconawesome_photo_video.png'),
    icUserTag: require('./imgAppJee/icIconawesome_user_tag.png'),
    icXoaAnh: require('./imgAppJee/icIconfeather_plus_circle.png'),
    icTouchChuaChon: require('./imgAppJee/icTouchChuaChon.png'),
    icTouchDaChon: require('./imgAppJee/icTouchDaChon.png'),
    icXoaLuaChon: require('./imgAppJee/icIconXoaLuaChon.png'),
    icThemLuaChon: require('./imgAppJee/icIconThemLuaChon.png'),
    icTickCheckThamGia: require('./imgAppJee/icTickCheckThamGia.png'),
    icKhongThamGia: require('./imgAppJee/icKhongThamGia.png'),
    icIconionic_ios_mail: require('./imgAppJee/icIconionic_ios_mail.png'),
    icDauHoi: require('./imgAppJee/icDauHoi.png'),
    icIconmaterial_people: require('./imgAppJee/icIconmaterial_people.png'),
    icIconmaterial_location_on: require('./imgAppJee/icIconmaterial_location_on.png'),
    icIconawesome_clock: require('./imgAppJee/icIconawesome_clock.png'),
    icCongNhom: require('./imgAppJee/icCongNhom.png'),
    icBangTinNhom: require('./imgAppJee/icBangTinNhom.png'),
    icThongBaoNhom: require('./imgAppJee/icThongBaoNhom.png'),
    icBangTinDaChon: require('./imgAppJee/icBangTinDaChon.png'),
    icThongBaoNhomDaChon: require('./imgAppJee/icThongBaoNhomDaChon.png'),
    icIConThemNguoiVaoNhom: require('./imgAppJee/icIConThemNguoiVaoNhom.png'),
    icTimKiemTextInput: require('./imgAppJee/icIconTimKiemSocial.png'),
    icSoLuotXem: require('./imgAppJee/icIconfeather_eye.png'),
    icSent: require('./imgAppJee/sent.png'),
    icGhim: require('./imgAppJee/pin.png'),
    icPlusThemTV: require('./imgAppJee/icPlusThemTV.png'),
    icTurnOnNoti: require('./imgAppJee/turnOnnotificationsbutton.png'),
    icTurnOffNoti: require('./imgAppJee/turnOffnotifications.png'),

    icBG1: require('./imgAppJee/BG1.png'),
    icBG2: require('./imgAppJee/BG2.png'),
    icBG3: require('./imgAppJee/BG3.png'),
    icBG4: require('./imgAppJee/BG4.png'),

    ic_DaLike: require('./imgAppJee/thumb-up.png'),
    icLove: require('./imgAppJee/heart.png'),
    icThuong: require('./imgAppJee/smile.png'),
    icHaHa: require('./imgAppJee/positive.png'),
    icWow: require('./imgAppJee/surprised.png'),
    icSad: require('./imgAppJee/anxiety.png'),
    icAngry: require('./imgAppJee/angry.png'),
    icTouchSocail: require('./imgAppJee/icTouchSocail.png'),
    icEditPhoto: require('./imgAppJee/upDatephoto.png'),
    icVideo: require('./imgAppJee/video.png'),
    //Request
    icStar: require('./imgAppJee/icStar.png'),
    icNoStar: require('./imgAppJee/icNoStar.png'),
    icFilter: require('./imgAppJee/icFilter.png'),
    icBrowser: require('./imgAppJee/icBrowser.png'),
    icUnBrowser: require('./imgAppJee/close.png'),
    icDropdown: require('./imgAppJee/icDropdown.png'),
    icPen: require('./imgAppJee/icPen.png'),
    icTick: require('./imgAppJee/icTick.png'),
    icDate: require('./imgAppJee/icDate.png'),
    icTime: require('./imgAppJee/icTime.png'),
    icIcon: require('./imgAppJee/icIcon.png'),
    icCamera: require('./imgAppJee/icCamera.png'),
    icImportFile: require('./imgAppJee/icImportFile.png'),
    icSearch: require('./imgAppJee/icSearch.png'),
    icIconMuc: require('./imgAppJee/icItemMuc.png'),
    icFilterr: require('./imgAppJee/icFilterr.png'),
    icImportGroup: require('./imgAppJee/icImportGroup.png'),
    icImportKind: require('./imgAppJee/icImportKind.png'),
    icSettingRequest: require('./imgAppJee/icSettingRequest.png'),
    icDropdownn: require('./imgAppJee/icDropdownn.png'),
    icPrint: require('./imgAppJee/icPrint.png'),
    icNhanBan: require('./imgAppJee/icNhanBan.png'),
    icDeleteRequest: require('./imgAppJee/icDeleteRequest.png'),
    icDropdownReverse: require('./imgAppJee/icDropdownReverse.png'),
    icNoDropDown: require('./imgAppJee/closeDropdown.png'),

    icAddPerson: require('./imgAppJee/icAddPerson.png'),
    icminumum: require('./imgAppJee/icminumum.png'),
    icSend: require('./imgAppJee/icSend.png'),
    icCloud: require('./imgAppJee/icCloud.png'),

    icjavacript: require('./imgAppJee/javascript.png'),
    icjpg: require('./imgAppJee/jpg.png'),
    icmp4: require('./imgAppJee/mp4.png'),
    icpdf: require('./imgAppJee/pdf.png'),
    icxml: require('./imgAppJee/xml.png'),
    iczip: require('./imgAppJee/zip.png'),
    ichtml: require('./imgAppJee/html.png'),
    icdoc: require('./imgAppJee/doc.png'),
    iccsv: require('./imgAppJee/csv.png'),
    iccss: require('./imgAppJee/css.png'),
    icfileDefault: require('./imgAppJee/fileDefault.png'),

    icGroup: require('./imgAppJee/group.png'),
    icDropdownColor: require('./imgAppJee/icDropdownColor.png'),

    icPlay: require('./imgAppJee/play-button.png'),
    icRightArrowMusic: require('./imgAppJee/right-arrow.png'),
    icLeftArrowMusic: require('./imgAppJee/left-arrow.png'),
    icPauseMusic: require('./imgAppJee/pause.png'),

    iclogoApp: require('./logoApp.png'),
    iclogoText: require('./logoText.png'),

    backgroundLogin: require('./imgAppJee/backgroundLogin.png'),
    logoLogin: require('./imgAppJee/logoLogin.png'),
    icloginUserName: require('./imgAppJee/loginUserName.png'),
    icloginPassWord: require('./imgAppJee/loginPassWord.png'),
    icCheckAllRead: require('./imgAppJeeHR/CheckAllRead.png'),
    icTouchRequest: require('./imgAppJee/icTouchRequest.png'),

    icThemCuocHop: require('./imgAppJee/icThemCuocHop.png'),
    icCHChon: require('./imgAppJee/icCHChon.png'),
    icCHChoXacNhan: require('./imgAppJee/icCHChoXacNhan.png'),
    icCHDaDat: require('./imgAppJee/icCHDaDat.png'),
    icCHRong: require('./imgAppJee/icCHRong.png'),
    icCHXacNhan: require('./imgAppJee/icCHXacNhan.png'),
    icZoom: require('./imgAppJee/icZoom.png'),
    icGoogleMeet: require('./imgAppJee/icGoogleMeet.png'),
    icReply: require('./imgAppJee/icReply.png'),
    icSmile: require('./imgAppJee/icSmile.png'),
    icMentions: require('./imgAppJee/mentions.png'),
    icMicro: require('./imgAppJee/microphone.png'),
    icDoubleCheck: require('./imgAppJee/doubleCheck.png'),
    icAddFile: require('./imgAppJee/icAddFile.png'),
    icMayChamCong: require('./imgAppJee/icMayChamCong.png'),
    icChamCongNV: require('./imgAppJee/icChamCongNV.png'),
    icDoubleSeen: require('./imgAppJee/doubleSeen.png'),
    UnCheckBlue: require('./imgAppJee/uncheckblue.png'),

    //chi tiết công việc quy trình
    ic_Dalam: require('./imgAppJee/ic_Dalam.png'),
    ic_Hoanthanh: require('./imgAppJee/ic_Hoanthanh.png'),
    ic_Thoigiannhan: require('./imgAppJee/ic_Thoigiannhan.png'),
    ic_Batdauluc: require('./imgAppJee/ic_Batdauluc.png'),
    ic_MuiTenDangLam: require('./imgAppJee/ic_MuiTenDangLam.png'),
    ic_Chinhsua: require('./imgAppJee/ic_Chinhsua.png'),
    ic_Themmoi: require('./imgAppJee/ic_ThemMoi.png'),
    ic_People: require('./imgAppJee/ic_People.png'),
    ic_adduserCVCTQT: require('./imgAppJee/ic_adduserCVCTQT.png'),
    ic_backCVCTQT: require('./imgAppJee/ic_backCVCTQT.png'),

    icCallChat: require('./imgAppJee/icCallChat.png'),
    icVideoChat: require('./imgAppJee/icVideoChat.png'),
    icKhoLuu: require('./imgAppJee/icKhoLuu.png'),
    icMeetingChat: require('./imgAppJee/icMeetingChat.png'),

    icQuaHan: require('./imgAppJee/icQuaHan.png'),
    tagcv: require('./imgAppJee/tagcv.png'),
    daucong: require('./imgAppJee/daucong.png'),
    icEarth: require('./imgAppJee/earth.png'),
    icCloseModal: require('./imgAppJee/closeModal.png'),
    icCalendarCheck: require('./imgAppJee/calendarCheck.png'),
    icModal: require('./imgAppJee/icModal.png'),
    CheckSort: require('./imgAppJee/checkSort.png'),
    icjpeg: require('./imgAppJee/icjpeg.png'),
    icmov: require('./imgAppJee/icmov.png'),
    icpng: require('./imgAppJee/icpng.png'),
    icCheckNhanSu: require('./imgAppJee/check.png'),
    icCloseNhanSu: require('./imgAppJee/close.png'),
    icAccepter: require('./imgAppJee/icAccepter.png'),
    icOClock: require('./imgAppJee/icOClock.png'),
    icClock: require('./imgAppJee/icClock.png'),
    icDateTime: require('./imgAppJee/icDateTime.png'),
    icManyPeople: require('./imgAppJee/icManyPeople.png'),
    jwTinhTrang: require('./imgAppJee/jwTinhTrang.png'),
    jwMucDo: require('./imgAppJee/jwMucDo.png'),
    jwTime: require('./imgAppJee/jwTime.png'),
    jwAddTime: require('./imgAppJee/jwAddTime.png'),
    ic_Ngaynhan: require('./imgAppJee/ic_Ngaynhan.png'),
    ic_Lydo: require('./imgAppJee/icLydo.png'),
    ic_ChoDuyet: require('./imgAppJee/ic_ChoDuyet.png'),
    icDahuy: require('./imgAppJee/icDahuy.png'),
    heic: require('./imgAppJee/heic.png'),
    icNgayDuyet: require('./imgAppJee/icNgayDuyet.png'),
    icProjectS: require('./imgAppJee/icProjectS.png'),
    icCalendarS: require('./imgAppJee/calendar.png'),
    ic_Loading: require('./imgAppJee/ic_loading.png'),
    icBackGroundMD: require('./imgAppJee/icBackGroundMD.png'),
    icAddPeople: require('./imgAppJee/add-contact.png'),
    icArrowsCircles: require('./imgAppJee/icArrowsCircles.png'),
    icBackJeeHR: require('./imgAppJee/backJeeHR.png'),
    icArrowRight: require('./imgAppJee/ArrowRight.png'),
    icAddDate: require('./imgAppJee/addDate.png'),
    icPlusJee: require('./imgAppJee/plusJee.png'),
    icTimeJee: require('./imgAppJee/timeJee.png'),
    icLockJee: require('./imgAppJee/lockJee.png'),
    icAddTimeJee: require('./imgAppJee/addTimeJee.png'),
    icNotFaceJee: require('./imgAppJee/NotFaceJee.png'),
    icCafeJee: require('./imgAppJee/cafeJee.png'),
    icClockJee: require('./imgAppJee/ClockJee.png'),
    icAttachJee: require('./imgAppJee/attachJee.png'),
    icAddgiaitrinh: require('./imgAppJee/addgiaitrinh.png'),
    icFilterJee: require('./imgAppJee/filterJee.png'),
    icTinhTrangJee: require('./imgAppJee/TinhTrangJee.png'),
    icUserJee: require('./imgAppJee/userJee.png'),
    icCoinJee: require('./imgAppJee/coinJee.png'),
    ic_LineTop: require('./imgAppJee/LineTop.png'),
    icPenJee: require('./imgAppJee/PenJee.png'),
    icWorkJee: require('./imgAppJee/workJee.png'),
    icTaiSanJee: require('./imgAppJee/taisanJee.png'),
    icDeleteJee: require('./imgAppJee/deleteJee.png'),
    icPhonghop: require('./imgAppJee/phonghop.png'),
    icListJee: require('./imgAppJee/listJee.png'),
    icCheckedJee: require('./imgAppJee/checkedJee.png'),
}

export const Images = {
    ImageJee,
    ...ImagesJeeHR,
    ...IConMenuHome,
    ...ImageTimekeeping,

};
